startdate:
  year: 2018
  month: 8
  day: 22

enddate:
  year: 2021
  month: 8
  day: 22

disqualified:
  - "+1"    # Typically used very often; kinda boring
  - "grin"
  # ...

nwinners: 15
npoints: 12